name: "api"  # 服务名称
mode: "dev"
ip: "127.0.0.1"
port: 3000
address: "127.0.0.1:3000"  # 服务地址
jwtSecret: "123456"  # jwt密码


log:
  level: "debug"
  filename: "api.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "139.196.81.60"
  port: 3306
  user: "mysql"
  password: "123456"
  dbname: "tiktok"
  max_open_conns: 100
  max_idle_conns: 10

consul:
  addr: "139.196.81.60:8500"

